THEMES = [
    "opening",
    "middlegame",
    "endgame",
    "oneMove",
    "short",
    "long",
    "veryLong",
    "mate",
    "advantage",
    "equality",
    "zugzwang",
    "castling",
    "defensiveMove",
]